---
- hosts: all
  sudo: yes
  vars_files:
    - [ "utils/vars/{{ ansible_distribution }}.yml", "utils/vars/os_defaults.yml" ]
  vars:
    ANSIBLE_VERSION: 1.7.2
  tasks:
    - name: Apt-get update
      apt: update_cache=yes cache_valid_time=604800
      when: ansible_os_family == "Debian"
      
    - name: Install libselinux-python in RH
      action: yum pkg=libselinux-python state=installed
      when: ansible_os_family == "RedHat"
      
    - name: Remove the python-crypto
      action: command rpm -e --nodeps python-crypto
      when: ansible_os_family == "RedHat"
      ignore_errors: True

    - name: EPEL
      #template: src=utils/templates/epel.repo dest=/etc/yum.repos.d/epel.repo
      template: src=utils/templates/epel-es.repo dest=/etc/yum.repos.d/epel.repo
      when: ansible_os_family == "RedHat"
    
    - name: Apt install requirements
      action: command apt-get -y install python-mysqldb unzip python-pip gcc python-dev
      when: ansible_os_family == "Debian"

    - name: Yum install requirements RH6 or Fedora
      action: command yum -y install python-distribute gcc python-devel wget
      when: ansible_os_family == "RedHat" and ansible_distribution_version|float >= 6.0
        
    - name: Yum install requirements RH5
      action: command yum -y install python26 python26-simplejson python26-distribute gcc python26-devel
      when: ansible_os_family == "RedHat" and ansible_distribution_version|float < 6.0
        
    - name: Install Pip 2.6
      action: command easy_install-2.6 pip==1.4.1
      when: ansible_os_family == "RedHat" and ansible_distribution_version|float < 6.0
      
    - name: Install Pip
      easy_install: name=pip
      when: ansible_os_family != "RedHat" or ansible_distribution_version|float >= 6.0
      register: result_install_pip
      ignore_errors: True

    - name: Install Pip (alternative)
      shell: wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py && python get-pip.py
      when: result_install_pip|failed

    - name: Link python 
      file: src=/usr/bin/python dest=/usr/bin/python_ansible state=link
      when: ansible_os_family != "RedHat" or ansible_distribution_version|float >= 6.0

    - name: Link python 2.6
      file: src=/usr/bin/python2.6 dest=/usr/bin/python_ansible state=link
      when: ansible_os_family == "RedHat" and ansible_distribution_version|float < 6.0

    - name: Install ansible with Pip
      pip: name=ansible version={{ ANSIBLE_VERSION }}
      when: ansible_os_family != "RedHat" or ansible_distribution_version|float >= 6.0
      
    - name: Install ansible with Pip 2.6
      action: command pip-2.6 install ansible=={{ ANSIBLE_VERSION }}
      when: ansible_os_family == "RedHat" and ansible_distribution_version|float < 6.0
      
    - name: Install pywinrm for windows support in ansible with Pip
      pip: name=http://github.com/diyan/pywinrm/archive/master.zip#egg=pywinrm
      when: ansible_os_family != "RedHat" or ansible_distribution_version|float >= 6.0
      
    - name: Install pywinrm for windows support in ansible with Pip 2.6
      action: command pip-2.6 install http://github.com/diyan/pywinrm/archive/master.zip#egg=pywinrm
      when: ansible_os_family == "RedHat" and ansible_distribution_version|float < 6.0

    - name: Disable SELinux
      command: /usr/sbin/setenforce 0
      when: ansible_os_family == "RedHat"
      ignore_errors: yes
      
    - name: Create /etc/ansible
      file: path=/etc/ansible state=directory
      
    - name: Set host_key_checking to false in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=host_key_checking value=False
      
    - name: Set transport to paramiko in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=transport value=paramiko

    - name: Set jinja2.ext.do to jinja2_extensions in ansible.cfg
      ini_file: dest=/etc/ansible/ansible.cfg section=defaults option=jinja2_extensions value=jinja2.ext.do
