  - name: Create DB {{name}}
    mysql_db: name={{name}} state=present login_user=root login_password={{root_password}}
  
  - name: Create user {{user}} for the DB {{name}}
    mysql_user: name={{user}} password={{password}} login_user=root login_password={{root_password}} priv={{name}}.*:ALL,GRANT state=present
